# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Multi-stage Dockerfile for MCP Server

# Builder stage: install dependencies and build
FROM node:lts-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and lockfile and tsconfig
COPY package.json package-lock.json tsconfig.json ./

# Install dependencies without running prepare scripts
RUN npm install --ignore-scripts

# Copy source files
COPY src ./src
COPY smithery.yaml ./

# Build TypeScript to JavaScript
RUN npm run build

# Runtime stage
FROM node:lts-alpine

WORKDIR /app

# Copy built files and dependencies from builder
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/smithery.yaml ./smithery.yaml

# Default command to start the MCP server
CMD ["node", "dist/index.js"]
